services:
  - type: web
    name: learn-math
    runtime: node
    plan: free
    repo: https://github.com/FractureV3/Learning-Math
    branch: main
    buildCommand: npm install
    startCommand: npm start
